---
type: "exposure"
phenotype_col: "Phenotype"
snp_col: "SNP"
beta_col: "beta"
se_col: "se"
eaf_col: "eaf"
effect_allele_col: "effect_allele"
other_allele_col: "other_allele"
pval_col: "pval"
units_col: "units"
ncase_col: "ncase"
ncontrol_col: "ncontrol"
samplesize_col: "samplesize"
gene_col: "gene"
id_col: "id"
z_col: "z"
info_col: "info"
chr_col: "chr"
pos_col: "pos"
# TODO: these are not column names
# snps: FALSE
# log_pval: FALSE
# min_pval: 1e-200
# header: TRUE
